variables:
  DEBFULLNAME: "Garden Linux builder"
  DEBEMAIL: "contact@gardenlinux.io"
  BUILD_ARCH_ALL: ''
  BUILD_ARCH_AMD64: 'true'
  BUILD_ARCH_ARM64: 'true'
  BUILD_SIGNED: ''
  ORIG_TAR: 'yes'
  SOURCE_NAME: 'sops'
  BUILD_REQUIRES_GO: 'true'

include:
- project: gardenlinux/gardenlinux-package-build
  file:
  - pipeline/pipeline.yml      


