#!/bin/bash

set -euEx
shopt -s failglob

function git() {
  command git -c advice.detachedHead=false "$@"
}

DEBIAN_REPO=''
DEBIAN_REF=''
SOURCE_NAME=${1:?Please specify source name}
UPSTREAM_VERSION=${2:?Please specify upstream version}
UPSTREAM_REPO=${3:?Please specify upstream repository}
UPSTREAM_REF=${4:?Please specify git tag or branch of upstream repository}

OUTPUT_DIR=$(mktemp -d -p "$(pwd)" "_orig_${UPSTREAM_VERSION}_XXXXXXXXXX")
trap 'rm -rf -- "$OUTPUT_DIR"' EXIT

# Get upstream sources
echo '### Cloning upstream repository'
git clone --quiet --depth 1 --branch "${UPSTREAM_REF}" "${UPSTREAM_REPO}" "${OUTPUT_DIR}/src"


# If specified, get release environment from a debian repo
if [[ -n "$DEBIAN_REPO" ]]; then
    # If not specified, use default branch from debian repo
    if [[ -n "$DEBIAN_REF" ]]; then
        echo '### cloning latest debian release environment'
        git clone --quiet --depth 1 "$DEBIAN_REPO" "${OUTPUT_DIR}/src"
    else
        echo "### cloning $DEBIAN_REF debian release environment"
        git clone --quiet --depth 1 --branch "$DEBIAN_REF" "$DEBIAN_REPO" "${OUTPUT_DIR}/src"
    fi
fi

echo '### generating a debian conform orig file'
(
  cd ${OUTPUT_DIR}
  ls src
  mv src "${SOURCE_NAME}-${UPSTREAM_VERSION}"
  tar -czf "${SOURCE_NAME}_${UPSTREAM_VERSION}.orig.tar.gz" "${SOURCE_NAME}-${UPSTREAM_VERSION}"
  ls
)

echo '### export orig via pristine-lfs'
pristine-lfs commit --force-overwrite "${OUTPUT_DIR}/${SOURCE_NAME}_${UPSTREAM_VERSION}.orig.tar.gz"

